project:
  type: website
  output-dir: docs

website:
  # Open Graph / Social Sharing

  open-graph:

    locale: en_US

    site-name: Jacob Jameson

    description: "PhD Candidate at Harvard studying health policy and decision sciences. NIMH Fellow researching suicide prevention, ED operations, and precision medicine."

    image: images/profile.png
  title: "Jacob Jameson"
  site-url: https://www.jacobjameson.com
  description: "Jacob Jameson's personal website"
  twitter-card:
    image: images/profile.png
    card-style: summary_large_image
    creator: "@JacobCJameson"
  page-footer:

    left: "Â© 2026 Jacob Jameson"

    right:

      - icon: envelope

        href: mailto:jacobjameson@g.harvard.edu

      - icon: github

        href: https://github.com/jacobjameson

      - icon: twitter

        href: https://twitter.com/JacobCJameson

    # Google Analytics (replace with your ID)

  google-analytics:

    tracking-id: "G-C0KP7Y1ZRW"

    anonymize-ip: true
  navbar:
    logo: "images/sig.png"
    align: center
    title: false
    collapse-below: lg
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-jameson
        target: _blank
      - icon: twitter
        href: https://twitter.com/JacobCJameson
        target: _blank
      - icon: github
        href: https://github.com/jacobjameson
        target: _blank
      - text: Blog
        href: posts/blog.qmd
      - text: Teaching
        menu:
          - text: "Jacob's Teaching Experience"
            href: teaching.qmd
          - text: "Introduction to R"
            href: R files/Intro R.qmd
          - text: "Introduction to Git/GitHub"
            href: git files/Intro Git.qmd
          - text: "API 222 Section Material"
            href: api 222 files/API222.qmd
      - text: Research
        href: research.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap

